### ISSUE TITLE
一个奇怪的事情

### ISSUE THREAD

**Issue by doubilbm** [chocotan/bili-recorder#1]
大佬您好，倒不是出了什么问题，一直在用这个给我自己做录播，因为b站没大文件上传权限的时候网页端只能传上限8G的视频，我设置的是一个半小时分一段，但是从28号开始分好段的就不上传只上传源文件，而源文件已经超过了8G，所以我就特别好奇是有什么办法可以绕过这个限制上传视频吗？

**Comment by chocotan** [comment]
阿B的文件大小限制好像是从客户端/网页端做的？直接调用API上传好像不会限制，所以可以绕过文件大小检查的样子。
网页端是8G不能多P，PC投稿工具是单个分P最大4G

**Comment by chocotan** [comment]
没想到居然还真有小伙伴用我这个项目

**Comment by doubilbm** [comment]
> 阿B的文件大小限制好像是从客户端/网页的？直接调用API上传端好像不会限制，所以可以绕过文件大小检查的基础。 网页端是8G不能多P，PC投稿工具是单独的分片P最大4G

懂了，谢谢

**Comment by chocotan** [comment]
不客气

doubilbm ***@***.***> 于2021年10月4日周一 下午8:28写道：
