### ISSUE TITLE
根据时间分好了段但是只上传源文件

### ISSUE THREAD

**Issue by doubilbm** [chocotan/bili-recorder#2]
(｡･∀･)ﾉﾞ嗨大佬又是我，之前那个issue也提了一嘴这个问题，但之前直接传源文件也能过审我就没怎么在意，但最近也不知道是时间太长（5-7个小时）还是文件过大（20G往上），导致b站老是卡转码审核过不了，只能手动上传就很麻烦  想问问有没有什么解决办法

**Comment by chocotan** [comment]
审核不通过的理由是什么？转码失败么？

**Comment by chocotan** [comment]
“根据时间分好了但是只上传源文件”——一般情况下是ffmpeg分割文件报错导致的，所以保留了源文件
可以提供一下程序运行的日志文件，在用户主目录/.bili/logs 目录下
6小时+的文件我这边没有遇到过问题诶

**Comment by doubilbm** [comment]
> “根据时间分好了但是只上传源文件”——一般情况下是ffmpeg分割文件报错导致的，所以保留了源文件 可以提供一下程序运行的日志文件，在用户主目录/.bili/logs 目录下 6小时+的文件我这边没有遇到过问题诶
[spring.log.2021-11-21.TXT](https://github.com/chocotan/bili-recorder/files/7580089/spring.log.2021-11-21.TXT)

**Comment by chocotan** [comment]
从日志上看，ffmpeg的处理速度较慢，ffmpeg的转换、分割逻辑还没有结束，上传投稿的任务就已经开始了
本周内会修复

**Comment by chocotan** [comment]
标题中提到的问题已修复，可以在这里下载：https://github.com/chocotan/bili-recorder/packages/951166

B站投稿的逻辑是：
文件分段分别上传->调用上传完成接口->调用投稿接口

日志中看到在第二步“调用完成上传接口” 处报错，接口返回500状态，内容是30秒超时，疑似是B站合并文件的处理超时了，分P可能会避免这个问题。
先试一下上面的新版吧。
